# Convenience targets. uv owns fdtdx/JAX (see README Environment); the meep
# env is only ever reached through the subprocess bridge (engines/meep_bridge.py).
# Every target here is a command, not a file. Without this, `make runs`
# silently does nothing because runs/ is a real directory and make decides it
# is already up to date -- the same trap waits for any target whose name
# collides with a path.
.PHONY: check gates test smoke smoke-meep phc-bend coupler-opt-smoke coupler-opt verify tolerance handoff runs help viz bootstrap pylock env-drift requirements bilingual

PY  ?= uv run python
GPU ?= $(if $(INVDX_GPU),$(INVDX_GPU),0)  # CUDA_VISIBLE_DEVICES for GPU-using targets

# One recipe, used twice: `pylock` writes it to the tracked path, `env-drift`
# writes it to a scratch path and diffs. Two separate command lines would be a
# checker that can silently stop matching what it checks.
#
# `--locked` makes the export fail rather than re-resolve when uv.lock has
# fallen behind pyproject.toml; `--no-header` drops uv's "autogenerated by the
# following command" banner, which embeds the output path and would therefore
# differ between the tracked file and the scratch copy. The banner is replaced
# by the fixed provenance block below, which is byte-identical either way.
define gen_pylock
	@printf '%s\n' \
	  '# pylock.toml -- PEP 751 lock for layer L1 (see docs/env.md).' \
	  '#' \
	  '# DERIVED FILE. uv.lock is the source of truth; this is an export of it' \
	  '# for installers that speak PEP 751 but not uv. Do not hand-edit:' \
	  '#     make pylock      regenerate, then commit the result' \
	  '#     make env-drift   fail if this file and uv.lock disagree' \
	  '#' \
	  '# Contents: core + gpu + dev, i.e. the environment scripts/bootstrap.sh' \
	  '# installs. Restore with:  uv pip sync pylock.toml' \
	  '' > $(1)
	@uv export --locked --format pylock.toml --extra gpu --extra dev --no-header >> $(1)
endef

# Targets taking RUN= fail inside Python with a path traceback when it is
# missing, which tells the reader nothing about what to type. Say it here.
define need_run
	@test -n "$(RUN)" || { \
	  echo "$@ needs a run directory:  make $@ RUN=runs/<dir>" >&2; \
	  echo "try 'make runs' to see which directories qualify" >&2; \
	  exit 2; }
endef

bootstrap:        ## install and verify layer L1 (uv/jax/fdtdx); safe to re-run
	bash scripts/bootstrap.sh

pylock:           ## regenerate pylock.toml from uv.lock (commit the result)
	$(call gen_pylock,pylock.toml)
	@echo "pylock.toml regenerated from uv.lock -- review and commit it"

# The L2 counterpart of this check is in docs/env.md: re-concretize into the
# tracked spack.lock and `git diff --exit-code` it. Same shape here, one level
# up: first ask uv whether uv.lock still matches pyproject.toml, then ask
# whether pylock.toml still matches uv.lock. No diff means the tracked files
# are still what the tracked intent produces.
env-drift:        ## fail if uv.lock is stale or pylock.toml has drifted from it
	@echo "==> uv.lock vs pyproject.toml"
	uv lock --check
	@echo "==> pylock.toml vs uv.lock"
	@tmp=$$(mktemp -t pylock.XXXXXX.toml); \
	 $(MAKE) --no-print-directory _pylock_to OUT=$$tmp; \
	 if diff -u pylock.toml $$tmp; then \
	   rm -f $$tmp; echo "==> no drift"; \
	 else \
	   rm -f $$tmp; \
	   echo "pylock.toml is not what uv.lock exports today." >&2; \
	   echo "Next: make pylock && git diff pylock.toml" >&2; \
	   exit 1; \
	 fi

.PHONY: _pylock_to
_pylock_to:       # internal: write the export to $(OUT); use `make pylock`
	$(call gen_pylock,$(OUT))

# Deliberately NOT tracked (see .gitignore). uv's own docs recommend against
# keeping a uv.lock and a requirements.txt side by side -- uv.lock expresses
# things requirements.txt cannot. This target exists only to feed tools that
# speak nothing else, chiefly `pip download` when building a wheelhouse for an
# air-gapped host (docs/env.md, "Offline / no-network reproduction").
#
# --no-emit-project is load-bearing, not tidiness: without it the export starts
# with `-e .`, and pip requires hashes for *all* requirements once any line
# carries one, so an editable line with nothing to hash fails the whole file.
requirements:     ## throwaway hash-pinned requirements.txt (not tracked)
	uv export --locked --format requirements.txt \
	    --extra gpu --extra dev --no-emit-project -o requirements.txt
	@echo "requirements.txt written -- scratch artifact, do not commit"

# `env-drift` above catches one copy of a fact going stale; this catches the
# other. Every document that exists in both English and Traditional Chinese is
# a pair, and the docs themselves name "the same fact written twice, only one
# copy updated" as the failure that produces no error signal. Without this
# target each pair is a future divergence.
#
# How many pairs there are is deliberately NOT written here: the checker counts
# them and prints the list every run, so the number lives in output that is
# regenerated rather than in a comment somebody has to remember to update. This
# comment used to say "11" and the answer had moved on.
#
# Plain python3, not $(PY): the script is stdlib-only on purpose, so a docs
# check runs on a bare clone before any environment exists. Making a Markdown
# lint depend on the JAX environment would be the wrong dependency edge.
#
# The self-test runs first, and its failure stops the target. It pins the one
# rule that tells the checker to ignore a match -- the ban exemption. A widened
# exemption still reports "OK", so the guard has to fail before the check that
# depends on it is believed.
bilingual:        ## check the English/Chinese doc pairs for mechanical drift
	@python3 scripts/check_bilingual.py --self-test
	@python3 scripts/check_bilingual.py

check:            ## gate G0 only: pure-python unit tests (a few minutes, CPU)
	$(PY) scripts/00_check.py --only unit

gates:            ## all validation gates in order (G0..G5)
	CUDA_VISIBLE_DEVICES=$(GPU) $(PY) scripts/00_check.py

test:             ## raw pytest (same tests G0 wraps)
	$(PY) -m pytest tests/ -q

smoke:            ## tiny forward fdtdx sim on GPU through config/cli/runio
	CUDA_VISIBLE_DEVICES=$(GPU) $(PY) scripts/01_smoke_fdtdx.py --tag smoke

smoke-meep:       ## round-trip of the meep-env subprocess bridge
	$(PY) scripts/02_smoke_meep_bridge.py

phc-bend:         ## literature benchmark, default stages (toy engine, CPU)
	$(PY) scripts/06_phc_bend.py --tag make

coupler-opt-smoke:   ## ~10 min: 4 iterations, proves the whole path runs
	CUDA_VISIBLE_DEVICES=$(GPU) $(PY) scripts/15_grating_coupler_optimize.py \
	    --tag smoke --iters 4 --set sim_time_s=0.3e-12

coupler-opt:         ## one inverse-design round on the grating coupler (~13 h, run detached)
	CUDA_VISIBLE_DEVICES=$(GPU) $(PY) scripts/15_grating_coupler_optimize.py --tag opt --gradcheck

verify:           ## second-engine check of a finished design: make verify RUN=runs/<dir>
	$(call need_run)
	CUDA_VISIBLE_DEVICES=$(GPU) $(PY) scripts/07_grating_coupler_verify_design.py --run $(RUN)

tolerance:        ## fabrication tolerance report: make tolerance RUN=runs/<dir> [LAMS=1.27,1.35,9]
	$(call need_run)
	$(PY) scripts/16_tolerance_report.py $(RUN) $(if $(LAMS),--lams $(LAMS))

handoff:          ## tool-neutral export for another solver: make handoff RUN=runs/<dir>
	$(call need_run)
	$(PY) -m invdx.export.handoff $(RUN)

runs:             ## which run directories can be fed to verify/tolerance/handoff
	@$(PY) tools/list_runs.py

help:
	@grep -E '^[a-z-]+:.*##' Makefile | sed 's/:.*##/  -/'

viz:              ## render figures from a run dir: make viz RUN=runs/<dir>
	$(call need_run)
	$(PY) -m invdx.viz $(RUN) --pdf
